apiVersion: apps/v1
kind: Deployment
metadata:
  name: "humongous-healthcare-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "humongous-healthcare-api"
  template:
    metadata:
      labels:
        app: "humongous-healthcare-api"
    spec:
      containers:
        - name: "humongous-healthcare-api"
          image: "taw5acrjrc26.azurecr.io/humongous-healthcare-api:0.0.0"
          env:
            - name: CosmosDb__Account
              valueFrom:
                secretKeyRef:
                  name: cosmosdb
                  key: cosmosdb-account
                  optional: false
            - name: CosmosDb__Key
              valueFrom:
                secretKeyRef:
                  name: cosmosdb
                  key: cosmosdb-key
                  optional: false
            - name: CosmosDb__DatabaseName
              value: HealthCheckDB
            - name: CosmosDb__ContainerName
              value: HealthCheck
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /HealthCheck
              port: http
          readinessProbe:
            httpGet:
              path: /HealthCheck
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
